version: 2.1
jobs:
  build-and-publish-image:
    docker:
      - image: cimg/node:17.9
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Build application
          command: |
            cd signaling-service
            yarn install --pure-lockfile
            yarn build
      - run:
          name: Publish Image
          command: |
            cd signaling-service
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker build -t signaling-service:latest .
            docker tag signaling-service:latest tuandanghtt1996/signaling-service:latest
            docker push tuandanghtt1996/signaling-service:latest
  deploy-application:
    docker:
      - image: python:3.11.4
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt update -y
            apt install -y sshpass
            apt install -y ansible
            ansible --version
      - run:
          name: Deploy application
          command: |
            cd ./ansible
            ansible-playbook -i hosts deploy.yml -e "ansible_port=24700 ansible_password=${SSH_PASSWORD} ansible_user=root"
workflows:
  deploy-workflow:
    jobs:
      - build-and-publish-image
      - deploy-application:
          requires:
            - build-and-publish-image