services:
  kurento:
    image: kurento/kurento-media-server:7.0
    hostname: kurento
    container_name: kurento
    expose:
      - "8888"
    ports:
      - 8899:8888
    networks:
      - kurento_network
  signaling:
    image: tuandanghtt1996/signaling-service:latest
    hostname: signaling-service
    container_name: signaling
    expose:
      - "8443"
    ports:
      - 8443:8443
    environment:
      - MEDIA_SERVER_HOST=kurento
      - MEDIA_SERVER_PORT=8888
      - APP_SERVER_HOST=localhost
      - APP_SERVER_PORT=8443
      - MONGODB_URL=mongodb://server_mongodb_media:27017
    networks:
      - kurento_network
  coturn:
    image: tuandanghtt1996/coturn:latest
    network_mode: host
    environment:
      - TURN_USERNAME=kurento
      - TURN_PASSWORD=kurento
  mongodb-media:
    container_name: server_mongodb_media
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    command: mongod --auth
    ports:
      - "37017:27017"
    expose:
      - 37018
    networks:
      - kurento_network
networks:
  kurento_network:
    driver: bridge