services:
  kurento:
    image: kurento/kurento-media-server:7.0
    hostname: kurento
    container_name: kurento
    expose:
      - "8888"
    ports:
      - 8888:8888
    networks:
      - kurento_network
  signaling:
    image: tuandanghtt1996/signaling-service:latest
    hostname: signaling-service
    container_name: signaling
    expose:
      - "8443"
    ports:
      - 8888:8888
    environment:
      - MEDIA_SERVER_HOST=103.56.163.217
      - MEDIA_SERVER_PORT=8888
      - APP_SERVER_HOST=103.56.163.217
      - APP_SERVER_PORT=8443
    networks:
      - kurento_network
  coturn:
    build:
      context: ./coturn
      dockerfile: Dockerfile
    network_mode: host
    environment:
      - TURN_USERNAME=kurento
      - TURN_PASSWORD=kurento
    ports:
      - '3478:3478/udp'
networks:
  kurento_network:
    driver: bridge