services:
  kurento:
    image: kurento/kurento-media-server:7.0
    hostname: kurento
    container_name: kurento
    expose:
      - "8888"
    ports:
      - 8899:8888
    networks:
      - kurento_network
    volumes:
      - ./media:/tmp
  coturn:
    image: tuandanghtt1996/coturn:latest
    network_mode: host
    environment:
      - TURN_USERNAME=kurento
      - TURN_PASSWORD=kurento
  signaling:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: signaling-service
    container_name: signaling
    expose:
      - "8444"
    ports:
      - 8444:8444
    environment:
      - MEDIA_SERVER_HOST=kurento
      - MEDIA_SERVER_PORT=8888
      - APP_SERVER_HOST=localhost
      - APP_SERVER_PORT=8444
    networks:
      - kurento_network
networks:
  kurento_network:
    driver: bridge
