volumes:
  mysql_data:
      driver: local

services:
  mysql:
      image: mysql:5.7
      volumes:
        - mysql_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password
  kurento:
    image: kurento/kurento-media-server:7.0
    hostname: kurento
    container_name: kurento
    environment:
      - GST_DEBUG="${GST_DEBUG:-2},KurentoUriEndpointImpl:5,uriendpoint:5,GST_URI:6,KurentoRecorderEndpointImpl:5,recorderendpoint:5,basemediamuxer:5,qtmux:5,curl*:5"
    expose:
      - "8888"
    ports:
      - 8899:8888
    networks:
      - kurento_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./media:/tmp
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - 4566:4566
    networks:
      - kurento_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  coturn:
    image: tuandanghtt1996/coturn:latest
    network_mode: host
    environment:
      - TURN_USERNAME=kurento
      - TURN_PASSWORD=kurento
#  signaling:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    hostname: signaling-service
#    container_name: signaling
#    expose:
#      - "8444"
#    ports:
#      - 8444:8444
#    environment:
#      - MEDIA_SERVER_HOST=kurento
#      - MEDIA_SERVER_PORT=8888
#      - APP_SERVER_HOST=localhost
#      - APP_SERVER_PORT=8444
#    networks:
#      - kurento_network
  mongodb-media:
    container_name: server_mongodb_media
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    command: mongod --auth
    ports:
      - "37017:27017"
    expose:
      - 37018
    networks:
      - kurento_network
  keycloak:
    image: quay.io/keycloak/keycloak:17.0.0
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin1
      KEYCLOAK_PASSWORD: admin1
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      - mysql
    command: start-dev
    healthcheck:
      test: "curl -f http://localhost:8080/admin || exit 1"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/  
networks:
  kurento_network:
    driver: bridge
